name: Run the Action

on:
  pull_request:

jobs:
  run-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run action
        uses: ./
